---

ip_loopback0: 6.6.6.6

leaf_spine_interfaces:
    - {intf: Ethernet1/9, intf_ip: 10.1.1.13, mask: 30 }
    - {intf: Ethernet1/10, intf_ip: 10.1.1.5, mask: 30 }
    
host_interfaces:
    - {intf: Ethernet1/1, vlan_id: 100}
