---

router bgp 65000
  router-id 5.5.5.5
  address-family ipv4 unicast
  address-family l2vpn evpn
  neighbor 3.3.3.3 remote-as 65000
    remote-as 65000
    update-source loopback0
    address-family ipv4 unicast
    address-family l2vpn evpn
      send-community extended
  neighbor 4.4.4.4 remote-as 65000
    remote-as 65000
    update-source loopback0
    address-family ipv4 unicast
    address-family l2vpn evpn
      send-community extended
  vrf vxlan
    address-family ipv4 unicast
      advertise l2vpn evpn
      redistribute direct route-map passall
      maximum-paths 32
      maximum-paths ibgp 32
