---

- name: get neighbors testing
  hosts: all
  connection: local
  gather_facts: no


  tasks:

    # retrieve details info and stats on an interface (from 'show interface')
    - nxos_get_interface: interface=mgmt0 host={{ inventory_hostname }}
