---

# Playbook : check_dc.yml
# Purpose : Compliance Check on various devices

#   2 Spines : Nexus 7k
#   2 Leafs : Nexus 9300


- hosts: spine
  roles:
    - role: check_spine

- hosts: leaf
  roles:
    - role: check_leaf

