---

# Playbook : provision_dc.yml
# Purpose : Provision the following topology

#   2 Spines : Nexus 7k
#   2 Leafs : Nexus 9300


- hosts: spine
  roles:
    - role: spine

- hosts: leaf
  roles:
    - role: leaf
